CREATE DATABASE rally_bd;
USE raLly_bd;

CREATE TABLE equipes (
	CODEQUIPE INTEGER PRIMARY KEY auto_increment,
	NOME_EQUIPE VARCHAR(200),
	PAIS_ORIGEM_EQUIPE VARCHAR(50)
);

CREATE TABLE pilotos (
	CODPILOTO INTEGER PRIMARY KEY auto_increment,
	NOME_PILOTO VARCHAR(200),
	NUM_LICENCA VARCHAR(20),
	PAIS_ORIGEM_PILOTO VARCHAR(50),
	TIPO_PILOTO VARCHAR(9),
	CONSTRAINT CHECK_TIPO_PILOTO (
		TIPO_PILOTO IN ('piloto', 'navegador', 'reserva')
	)
);

CREATE TABLE fabricantes (
	CODFABRICANTE INTEGER PRIMARY KEY auto_increment,
	NOME_FABRICANTE VARCHAR(200),
	PAIS_ORIGEM_FABRICANTE VARCHAR(50)
);

CREATE TABLE categorias (
	CODCATEGORIA INTEGER PRIMARY KEY auto_increment,
	NOME_CATEGORIA VARCHAR(200)
);

CREATE TABLE modelos (
	CODMODELO INTEGER PRIMARY KEY auto_increment,
	NOME_MODELO VARCHAR(200),
	NUM_MODELO VARCHAR(20),
	DESCRICAO_MODELO TEXT,
	POTENCIA VARCHAR(20),
	CODFABRICANTE INTEGER NOT NULL, 
	CODCATEGORIA INTEGER NOT NULL,
	FOREIGN KEY (CODFABRICANTE) REFERENCES fabricantes(CODFABRICANTE) ON UPDATE RESTRICT ON DELETE RESTRICT,
	FOREIGN KEY (CODCATEGORIA) REFERENCES categorias(CODCATEGORIA) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE campeonatos (
	CODCAMPEONATO INTEGER PRIMARY KEY auto_increment,
	ANO_CAMPEONATO YEAR,
	EDICAO DECIMAL(3,0)
);

CREATE TABLE inscricoes (
	CODCAMPEONATO INTEGER NOT NULL,
	CODCATEGORIA INTEGER NOT NULL,
	PRIMARY KEY (CODCAMPEONATO, CODCATEGORIA),
	FOREIGN KEY (CODCAMPEONATO) REFERENCES campeonatos(CODCAMPEONATO) ON UPDATE RESTRICT ON DELETE RESTRICT,
	FOREIGN KEY (CODCATEGORIA) REFERENCES categorias(CODCATEGORIA) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE carros (
	CODCARRO INTEGER PRIMARY KEY auto_increment,
	NUM_CARRO VARCHAR(20),
	CODEQUIPE INTEGER NOT NULL,
	CODMODELO INTEGER NOT NULL,
	CODPILOTO INTEGER  NOT NULL,
	CODNAVEGADOR INTEGER NOT NULL,
	CODCATEGORIA INTEGER NOT NULL,
	CODCAMPEONATO INTEGER NOT NULL,
	FOREIGN KEY (CODEQUIPE) REFERENCES equipes(CODEQUIPE) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (CODMODELO) REFERENCES modelos(CODMODELO) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (CODPILOTO) REFERENCES pilotos(CODPILOTO) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (CODNAVEGADOR) REFERENCES pilotos(CODPILOTO) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (CODCATEGORIA) REFERENCES categorias(CODCATEGORIA) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (CODCAMPEONATO) REFERENCES campeonatos(CODCAMPEONATO) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE etapas (
	CODETAPA INTEGER,
	CODCAMPEONATO INTEGER NOT NULL,
	NOME_ETAPA VARCHAR(200),
	PAIS_ORIGEM_ETAPA VARCHAR(50),
	DATA_REALIZACAO DATE,
	CIDADE VARCHAR(50),
	NUM_ETAPA VARCHAR(20),
	PRIMARY KEY (CODETAPA, CODCAMPEONATO),
	FOREIGN KEY (CODCAMPEONATO) REFERENCES campeonatos(CODCAMPEONATO) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE trechos (
	CODTRECHO INTEGER,
	CODETAPA INTEGER NOT NULL,
	CODCAMPEONATO INTEGER NOT NULL,
	TEMPO_PREVISTO_REALIZACAO TIME,
	NUM_TRECHO VARCHAR(20),
	PRIMARY KEY(CODTRECHO, CODETAPA, CODCAMPEONATO),
	FOREIGN KEY (CODETAPA) REFERENCES etapas(CODETAPA) ON UPDATE RESTRICT ON DELETE RESTRICT,
	FOREIGN KEY (CODCAMPEONATO) REFERENCES campeonatos(CODCAMPEONATO) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE percursos (
	CODCARRO INTEGER NOT NULL,
	CODTRECHO INTEGER NOT NULL,
	CODETAPA INTEGER NOT NULL,
	CODCAMPEONATO INTEGER NOT NULL,
	TEMPO_REALIZADO TIME,
	QUANT_PONTO INTEGER,
	PRIMARY KEY(CODTRECHO, CODETAPA, CODCAMPEONATO, CODCARRO)
	FOREIGN KEY (CODCARRO) REFERENCES carros(CODCARRO) ON UPDATE RESTRICT ON DELETE RESTRICT,
	FOREIGN KEY (CODTRECHO) REFERENCES trechos(CODTRECHO) ON UPDATE RESTRICT ON DELETE RESTRICT,
	FOREIGN KEY (CODETAPA) REFERENCES etapas(CODETAPA) ON UPDATE RESTRICT ON DELETE RESTRICT,
	FOREIGN KEY (CODCAMPEONATO) REFERENCES campeonatos(CODCAMPEONATO) ON UPDATE RESTRICT ON DELETE RESTRICT
	
);

--Trigger para CODPILOTO e CODNAVEGADOR
DELIMITER $$
CREATE TRIGGER validar_piloto_navegador
BEFORE INSERT ON carros
FOR EACH ROW
BEGIN
	DECLARE tipo_encontrado CHAR(9);
	SELECT TIPO_PILOTO INTO tipo_encontrado
		FROM pilotos
		WHERE CODPILOTO = NEW.CODPILOTO
	IF tipo_encontrado IS NULL OR 
		tipo_encontrado NOT IN ('piloto', 'reserva') THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'Erro no CODPILOTO na inserção de novo carro';
	END IF;
	SELECT TIPO_PILOTO INTO tipo_encontrado
		FROM pilotos
		WHERE CODPILOTO = NEW.CODNAVEGADOR
	IF tipo_encontrado IS NULL OR
		tipo_encontrado NOT IN ('navegador', 'reserva') THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'Erro no CODNAVEGADOR na inserção de novo carro';
	END IF;
END $$